### ISSUE TITLE
Local 2

### ISSUE THREAD

**Issue by GaryJones** [tpkemme/local-addon-plugins-themes#2]
The current engine is set as `"local-by-flywheel": "^1.1.0"`. Obviously, this doesn't satisfy it being used with Local 2.

Will the code work as is (and if so, can the engine requirement allow for 2 as well), or will it need further work?

**Comment by tpkemme** [comment]
Hey @GaryJones thanks for the update.  Theoretically the code should work by changing `"local-by-flywheel": "^1.1.0"` to `"local-by-flywheel": "^2.0.0"` (it worked successfully on the [Local Dev Tools Addon](https://github.com/tpkemme/local-addon-devtools)).  However, I tried updating the engine for this addon and I experiencing errors.  I'm almost positive I've solved these issues in the past, I believe the error is caused because Flywheel names their application "Local by Flywheel" and the spaces between each word are throwing off one of the bash scripts.  I think in the past I solved this by renaming the application to just "Local" but I'm looking for a real solution before I push up the update.

**Comment by GaryJones** [comment]
Changing the engine to `"local": "^2.0.0"` does seem to allow it to install, but I don't see anything under More.

**Comment by tpkemme** [comment]
did you activate the plugin in the settings menu?  the local machine also needs to be restarted after you activate an addon

**Comment by GaryJones** [comment]
Thanks! Though I don't see it under More still. (I cleared out the old add-on, restarted Local and the site)
![screenshot 2017-06-15 08 26 42](https://user-images.githubusercontent.com/88371/27170052-7313fb12-51a4-11e7-8e45-235a10941bda.png)

Turning off the other plugins, just means the More menu doesn't appear at all.
![screenshot 2017-06-15 08 28 07](https://user-images.githubusercontent.com/88371/27170101-9527ab86-51a4-11e7-9d7f-7fbbfde569a4.png)



Aside: A new gif for the readme would help show it's for Local v2 :-)

**Comment by tpkemme** [comment]
Weird.. I wonder if it maybe it's a conflict with one of the other addons.  I'll take a look at it later today.
